# Welcome to Jekyll!
#

# Site settings
title: Megajuegos
description: |
  Un juego de tablero,  
  mezcla de Estrategia, Diplomacia y Negociación,  
  para 50 o más jugadores simultáneos.
owner: Megajuegos Argentina # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: megajuegos@protocultura.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.megajuegos.com.ar" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/megajuegosARG
  github: https://github.com/megajuegos/megajuegos.github.io
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/megajuegosARG
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: contact.html
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
